version: "3"


services:

  identity-and-access-app:
    image: diaspogift/identity-and-access
    networks:
      - iam-network
    ports:
      - 80:8080
    depends_on:
      - identity-and-access-database



  identity-and-access-database:
    image: mysql
    networks:
      - iam-network
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=identityandaccess


  identity-and-access-ui:
    image: diaspogift/identity-and-access-ui
    networks:
      - iam-network
    ports:
      - 8090:4200




networks:

  iam-network:
